name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Website validation with Pester
        continue-on-error: true
        run: pwsh -Command Invoke-Pester -Path ".github/powershell/validation.ps1" -OutputFile "results.xml" -OutputFormat NUnitXml
      
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            result.xml
